export const ACTIONS = {
  // Settings
  SET_MODEL: "SET_MODEL",
  SET_SYSTEM_PROMPT: "SET_SYSTEM_PROMPT",
  SET_TEMPERATURE: "SET_TEMPERATURE",
  SET_MAX_TOKENS: "SET_MAX_TOKENS",
  TOGGLE_MEMORY: "TOGGLE_MEMORY",
  SET_CUTOFF: "SET_CUTOFF",

  // Conversation
  ADD_USER_MESSAGE: "ADD_USER_MESSAGE",
  CLEAR_MESSAGES: "CLEAR_MESSAGES",

  // Streaming
  START_STREAM: "START_STREAM",
  APPEND_TOKEN: "APPEND_TOKEN",
  FINISH_STREAM: "FINISH_STREAM",
  STREAM_ERROR: "STREAM_ERROR",

  // UI
  CLEAR_ERROR: "CLEAR_ERROR",
};
