export const ACTIONS = {
  // Settings
  SET_MODEL: "SET_MODEL",
  SET_SYSTEM_PROMPT: "SET_SYSTEM_PROMPT",
  SET_TEMPERATURE: "SET_TEMPERATURE",
  SET_MAX_TOKENS: "SET_MAX_TOKENS",
  TOGGLE_MEMORY: "TOGGLE_MEMORY",
  SET_CUTOFF: "SET_CUTOFF",

  // API Keys
  SET_GROQ_KEY: "SET_GROQ_KEY",
  SET_NVIDIA_KEY: "SET_NVIDIA_KEY",

  // Conversations
  NEW_CONVERSATION: "NEW_CONVERSATION",
  SWITCH_CONVERSATION: "SWITCH_CONVERSATION",
  SET_TITLE: "SET_TITLE",

  // Streaming
  ADD_USER_MESSAGE: "ADD_USER_MESSAGE",
  START_STREAM: "START_STREAM",
  APPEND_TOKEN: "APPEND_TOKEN",
  FINISH_STREAM: "FINISH_STREAM",
  STREAM_ERROR: "STREAM_ERROR",

  // App lifecycle
  LOAD_STATE: "LOAD_STATE",

  // UI
  CLEAR_ERROR: "CLEAR_ERROR",
};
