export const ACTIONS = {
  // Settings
  SET_MODEL: "SET_MODEL",
  SET_SYSTEM_PROMPT: "SET_SYSTEM_PROMPT",
  SET_TEMPERATURE: "SET_TEMPERATURE",
  SET_MAX_TOKENS: "SET_MAX_TOKENS",
  TOGGLE_MEMORY: "TOGGLE_MEMORY",
  SET_CUTOFF: "SET_CUTOFF",

  // API Keys
  SET_GROQ_KEY: "SET_GROQ_KEY",
  SET_NVIDIA_KEY: "SET_NVIDIA_KEY",

  // Conversations
  NEW_CONVERSATION: "NEW_CONVERSATION",
  SWITCH_CONVERSATION: "SWITCH_CONVERSATION",
  SET_TITLE: "SET_TITLE",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  RENAME_CONVERSATION: "RENAME_CONVERSATION",
  SET_CONVERSATION_COLOR: "SET_CONVERSATION_COLOR",

  // Groups
  CREATE_GROUP: "CREATE_GROUP",
  RENAME_GROUP: "RENAME_GROUP",
  SET_GROUP_COLOR: "SET_GROUP_COLOR",
  DELETE_GROUP: "DELETE_GROUP",
  TOGGLE_GROUP_COLLAPSED: "TOGGLE_GROUP_COLLAPSED",
  MOVE_CONVERSATION_TO_GROUP: "MOVE_CONVERSATION_TO_GROUP",
  TOGGLE_GROUP_RAG: "TOGGLE_GROUP_RAG",

  // Discord Mode
  TOGGLE_REACTION: "TOGGLE_REACTION",

  // Streaming
  ADD_USER_MESSAGE: "ADD_USER_MESSAGE",
  START_STREAM: "START_STREAM",
  APPEND_TOKEN: "APPEND_TOKEN",
  FINISH_STREAM: "FINISH_STREAM",
  STREAM_ERROR: "STREAM_ERROR",

  // Compress
  COMPRESS_CONVERSATION: "COMPRESS_CONVERSATION",

  // App lifecycle
  LOAD_STATE: "LOAD_STATE",

  // UI
  CLEAR_ERROR: "CLEAR_ERROR",
  SET_THEME: "SET_THEME",
  SET_LANGUAGE: "SET_LANGUAGE",
};
